
package CapaInterfaz;

import CapaNegocio.ClsCirculo;
import CapaNegocio.ClsCuadrilatero;
import CapaNegocio.ClsPoligono;
import CapaNegocio.ClsTriangulo;
import java.awt.MenuItem;

public class WinFigura extends javax.swing.JFrame {

    /**
     * Creates new form WinFigura
     */
    public WinFigura() {
        initComponents();
        PnlTriangulo.setVisible(false);
        PnlCuadrilatero.setVisible(false);
        PnlCirculo.setVisible(false);
        PnlPoligono.setVisible(false);
    }
    ClsCirculo a;
    ClsTriangulo b;
    int lado1,lado2,lado3,lado4;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        PnlTriangulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtLado1 = new javax.swing.JTextField();
        TxtLado2 = new javax.swing.JTextField();
        TxtLado3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        PnlCirculo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        PnlCuadrilatero = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        PnlPoligono = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        PnlResultados = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblFigura = new javax.swing.JLabel();
        LblTipoCalculo = new javax.swing.JLabel();
        LblValor = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuTriangulo = new javax.swing.JMenu();
        ItmTrgArea = new javax.swing.JMenuItem();
        ItmTrgPerimetro = new javax.swing.JMenuItem();
        ItmTrgTipo = new javax.swing.JMenuItem();
        MnuCuadrilatero = new javax.swing.JMenu();
        ItmCuadArea = new javax.swing.JMenuItem();
        ItmCuadPerimetro = new javax.swing.JMenuItem();
        MnuCirculo = new javax.swing.JMenu();
        ItmCirArea = new javax.swing.JMenuItem();
        ItmCirPerimetro = new javax.swing.JMenuItem();
        MnuPoligono = new javax.swing.JMenu();
        ItmPolArea = new javax.swing.JMenuItem();
        ItmPolPerimetro = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TRIANGULO");

        jLabel2.setText("Lado 1:");

        jLabel3.setText("Lado 2:");

        jLabel4.setText("Lado 3:");

        jButton1.setText("Retornar");

        javax.swing.GroupLayout PnlTrianguloLayout = new javax.swing.GroupLayout(PnlTriangulo);
        PnlTriangulo.setLayout(PnlTrianguloLayout);
        PnlTrianguloLayout.setHorizontalGroup(
            PnlTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTrianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlTrianguloLayout.createSequentialGroup()
                        .addGroup(PnlTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PnlTrianguloLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtLado1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlTrianguloLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtLado3))
                            .addGroup(PnlTrianguloLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtLado2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTrianguloLayout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addGroup(PnlTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTrianguloLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(164, 164, 164))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTrianguloLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(39, 39, 39))))))
        );
        PnlTrianguloLayout.setVerticalGroup(
            PnlTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTrianguloLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PnlTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtLado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(PnlTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtLado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtLado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jLabel9.setText("CIRCULO");

        jLabel10.setText("Radio:");

        jButton3.setText("Retornar");

        javax.swing.GroupLayout PnlCirculoLayout = new javax.swing.GroupLayout(PnlCirculo);
        PnlCirculo.setLayout(PnlCirculoLayout);
        PnlCirculoLayout.setHorizontalGroup(
            PnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCirculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlCirculoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCirculoLayout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(164, 164, 164))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCirculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );
        PnlCirculoLayout.setVerticalGroup(
            PnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCirculoLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(PnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(21, 21, 21))
        );

        jLabel13.setText("CUADRILATERO");

        jLabel14.setText("Lado 1:");

        jLabel15.setText("Lado 2:");

        jButton4.setText("Retornar");

        javax.swing.GroupLayout PnlCuadrilateroLayout = new javax.swing.GroupLayout(PnlCuadrilatero);
        PnlCuadrilatero.setLayout(PnlCuadrilateroLayout);
        PnlCuadrilateroLayout.setHorizontalGroup(
            PnlCuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCuadrilateroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlCuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlCuadrilateroLayout.createSequentialGroup()
                        .addGroup(PnlCuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PnlCuadrilateroLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlCuadrilateroLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCuadrilateroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(164, 164, 164))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCuadrilateroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(109, 109, 109))
        );
        PnlCuadrilateroLayout.setVerticalGroup(
            PnlCuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCuadrilateroLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(PnlCuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(PnlCuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(87, 87, 87))
        );

        jLabel17.setText("POLIGONO");

        jLabel18.setText("Numero de lados:");

        jLabel19.setText("Lados:");

        jButton5.setText("Retornar");

        javax.swing.GroupLayout PnlPoligonoLayout = new javax.swing.GroupLayout(PnlPoligono);
        PnlPoligono.setLayout(PnlPoligonoLayout);
        PnlPoligonoLayout.setHorizontalGroup(
            PnlPoligonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPoligonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlPoligonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlPoligonoLayout.createSequentialGroup()
                        .addGroup(PnlPoligonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PnlPoligonoLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlPoligonoLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField14)))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlPoligonoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(164, 164, 164))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlPoligonoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(18, 18, 18))
        );
        PnlPoligonoLayout.setVerticalGroup(
            PnlPoligonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPoligonoLayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(PnlPoligonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(PnlPoligonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap())
        );

        LblTitulo.setText("RESULTADOS");

        javax.swing.GroupLayout PnlResultadosLayout = new javax.swing.GroupLayout(PnlResultados);
        PnlResultados.setLayout(PnlResultadosLayout);
        PnlResultadosLayout.setHorizontalGroup(
            PnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlResultadosLayout.createSequentialGroup()
                        .addComponent(LblTipoCalculo, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(PnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LblFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblTitulo)))
                .addGap(18, 18, 18)
                .addComponent(LblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnlResultadosLayout.setVerticalGroup(
            PnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlResultadosLayout.createSequentialGroup()
                .addComponent(LblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTipoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        MnuTriangulo.setText("Triangulo");
        MnuTriangulo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MnuTrianguloMenuSelected(evt);
            }
        });
        MnuTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuTrianguloActionPerformed(evt);
            }
        });

        ItmTrgArea.setText("Area");
        ItmTrgArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmTrgAreaActionPerformed(evt);
            }
        });
        MnuTriangulo.add(ItmTrgArea);

        ItmTrgPerimetro.setText("Perimetro");
        MnuTriangulo.add(ItmTrgPerimetro);

        ItmTrgTipo.setText("Tipo");
        MnuTriangulo.add(ItmTrgTipo);

        jMenuBar1.add(MnuTriangulo);

        MnuCuadrilatero.setText("Cuadrilatero");
        MnuCuadrilatero.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MnuCuadrilateroMenuSelected(evt);
            }
        });
        MnuCuadrilatero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCuadrilateroActionPerformed(evt);
            }
        });

        ItmCuadArea.setText("Area");
        MnuCuadrilatero.add(ItmCuadArea);

        ItmCuadPerimetro.setText("Perimetro");
        MnuCuadrilatero.add(ItmCuadPerimetro);

        jMenuBar1.add(MnuCuadrilatero);

        MnuCirculo.setText("Circulo");
        MnuCirculo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MnuCirculoMenuSelected(evt);
            }
        });

        ItmCirArea.setText("Area");
        MnuCirculo.add(ItmCirArea);

        ItmCirPerimetro.setText("Perimetro");
        MnuCirculo.add(ItmCirPerimetro);

        jMenuBar1.add(MnuCirculo);

        MnuPoligono.setText("Poligono");
        MnuPoligono.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MnuPoligonoMenuSelected(evt);
            }
        });

        ItmPolArea.setText("Area");
        ItmPolArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmPolAreaActionPerformed(evt);
            }
        });
        MnuPoligono.add(ItmPolArea);

        ItmPolPerimetro.setText("Perimetro");
        MnuPoligono.add(ItmPolPerimetro);

        jMenuBar1.add(MnuPoligono);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PnlTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PnlCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PnlPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PnlCuadrilatero, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(PnlResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PnlCuadrilatero, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PnlCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PnlPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(PnlResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItmPolAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmPolAreaActionPerformed
        //lado1=Integer.parseInt(TxtLado1.Triangulo);
    }//GEN-LAST:event_ItmPolAreaActionPerformed

    private void MnuTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuTrianguloActionPerformed
        PnlTriangulo.setVisible(true);
        PnlCuadrilatero.setVisible(false);
        PnlCirculo.setVisible(false);
        PnlPoligono.setVisible(false);
        PnlResultados.setVisible(false);
    }//GEN-LAST:event_MnuTrianguloActionPerformed

    private void MnuCuadrilateroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCuadrilateroActionPerformed
         PnlTriangulo.setVisible(false);
        PnlCuadrilatero.setVisible(true);
        PnlCirculo.setVisible(false);
        PnlPoligono.setVisible(false);
        PnlResultados.setVisible(false);
    }//GEN-LAST:event_MnuCuadrilateroActionPerformed

    private void MnuTrianguloMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuTrianguloMenuSelected
        PnlTriangulo.setVisible(true);
        PnlCuadrilatero.setVisible(false);
        PnlCirculo.setVisible(false);
        PnlPoligono.setVisible(false);
        PnlResultados.setVisible(false);
        
    }//GEN-LAST:event_MnuTrianguloMenuSelected

    private void MnuCuadrilateroMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuCuadrilateroMenuSelected
        PnlTriangulo.setVisible(false);
        PnlCuadrilatero.setVisible(true);
        PnlCirculo.setVisible(false);
        PnlPoligono.setVisible(false);
        PnlResultados.setVisible(false);
    }//GEN-LAST:event_MnuCuadrilateroMenuSelected

    private void MnuCirculoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuCirculoMenuSelected
         PnlTriangulo.setVisible(false);
        PnlCuadrilatero.setVisible(false);
        PnlCirculo.setVisible(true);
        PnlPoligono.setVisible(false);
        PnlResultados.setVisible(false);
    }//GEN-LAST:event_MnuCirculoMenuSelected

    private void MnuPoligonoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MnuPoligonoMenuSelected
         PnlTriangulo.setVisible(false);
        PnlCuadrilatero.setVisible(false);
        PnlCirculo.setVisible(false);
        PnlPoligono.setVisible(true);
        PnlResultados.setVisible(false);
    }//GEN-LAST:event_MnuPoligonoMenuSelected

    private void ItmTrgAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmTrgAreaActionPerformed
        
    }//GEN-LAST:event_ItmTrgAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinFigura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItmCirArea;
    private javax.swing.JMenuItem ItmCirPerimetro;
    private javax.swing.JMenuItem ItmCuadArea;
    private javax.swing.JMenuItem ItmCuadPerimetro;
    private javax.swing.JMenuItem ItmPolArea;
    private javax.swing.JMenuItem ItmPolPerimetro;
    private javax.swing.JMenuItem ItmTrgArea;
    private javax.swing.JMenuItem ItmTrgPerimetro;
    private javax.swing.JMenuItem ItmTrgTipo;
    private javax.swing.JLabel LblFigura;
    private javax.swing.JLabel LblTipoCalculo;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblValor;
    private javax.swing.JMenu MnuCirculo;
    private javax.swing.JMenu MnuCuadrilatero;
    private javax.swing.JMenu MnuPoligono;
    private javax.swing.JMenu MnuTriangulo;
    private javax.swing.JPanel PnlCirculo;
    private javax.swing.JPanel PnlCuadrilatero;
    private javax.swing.JPanel PnlPoligono;
    private javax.swing.JPanel PnlResultados;
    private javax.swing.JPanel PnlTriangulo;
    private javax.swing.JTextField TxtLado1;
    private javax.swing.JTextField TxtLado2;
    private javax.swing.JTextField TxtLado3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
